/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/site-packages/transformers/utils/hub.py:127: FutureWarning: Using `TRANSFORMERS_CACHE` is deprecated and will be removed in v5 of Transformers. Use `HF_HOME` instead.
  warnings.warn(
Attack started at: 2024-07-24 21:21
Namespace(llm_name='ollama/gemma2:9b', max_gpu_memory=None, eval_device=None, max_new_tokens=512, scheduler_log_mode='console', agent_log_mode='console', llm_kernel_log_mode='console', use_backend=None, workflow_mode='automatic', attacker_tools_path='data/attacker_cases_dh.jsonl', tasks_path='data/agent_tasks/example/currencyexchange_agent_tasks.txt', agent_path='example/currencyexchange_agent', observation_prompt_injection=False, plan_attack=False, action_attack=False, direct_prompt_injection=False, attack_type=None, cot_backdoor=False)
[ðŸ¤–ollama/gemma2:9b] AIOS LLM successfully loaded.

Traceback (most recent call last):
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 162, in <module>
    main()
  File "/common/users/hz624/AgentAttackBench/main_attacker.py", line 127, in main
    for r in as_completed(agent_tasks):
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/concurrent/futures/_base.py", line 243, in as_completed
object address  : 0x7f5e3a336200
object refcount : 2
object type     : 0x879400
object type name: KeyboardInterrupt
object repr     : KeyboardInterrupt()
lost sys.stderr
Exception ignored in: <module 'threading' from '/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/threading.py", line 1560, in _shutdown
  File "/common/home/hz624/anaconda3/envs/AIOS/lib/python3.11/concurrent/futures/thread.py", line 31, in _python_exit
KeyboardInterrupt: 
